# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gem-whois 0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "gem-whois".freeze
  s.version = "0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["David Dollar".freeze]
  s.date = "2016-03-14"
  s.email = "<ddollar@gmail.com>".freeze
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "lib/gem/commands/whois_command.rb",
    "lib/rubygems_plugin.rb"
  ]
  s.homepage = "http://github.com/ddollar/gem-whois".freeze
  s.rubygems_version = "2.6.1".freeze
  s.summary = "Show information about the owner of a gem".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<crack>.freeze, ["~> 0.4.3"])
    else
      s.add_dependency(%q<crack>.freeze, ["~> 0.4.3"])
    end
  else
    s.add_dependency(%q<crack>.freeze, ["~> 0.4.3"])
  end
end

